<?xml version="1.0"?>

<robot name="thor_mang_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find thor_mang_description)/urdf/arm/thor_arm_7dof_simple.urdf.xacro" />
  
  <xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_mesh_visual_geoms.urdf.xacro.xml" />
  <xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_primitive_collision_geoms.urdf.xacro.xml" />

  <xacro:include filename="$(find thor_mang_description)/robots/offsets/thor_mang_zero_offsets.urdf.xacro.xml" />      
  
  <link
    name="utorso">
    <xacro:inertial_cuboid__with_pose_macro mass="10.91" x_length="0.25" y_length="0.3" z_length="0.2" >
      <origin xyz="-0.0264 0.0 0.155" rpy="0 0 0"/>
    </xacro:inertial_cuboid__with_pose_macro>
    <xacro:utorso_visual_geom_macro />
    <xacro:utorso_collision_geom_macro />
  </link>
  
  <thor_arm_7dof_simple_with_offsets_macro parent="utorso" name="l" reflect="1"        
     arm_joint_0_limit_lower="${-M_PI}"
     arm_joint_0_limit_upper="${2.3}"
     arm_joint_1_limit_lower="${-M_PI}"
     arm_joint_1_limit_upper="${0.05}" 
     arm_joint_2_limit_lower="${-M_PI*0.5}"
     arm_joint_2_limit_upper="${M_PI}" 
     arm_joint_3_limit_lower="${-2.9}" 
     arm_joint_3_limit_upper="${0.6}"
     arm_joint_4_limit_lower="${-M_PI}"
     arm_joint_4_limit_upper="${4.71}"  
     arm_joint_5_limit_lower="${-1.47}"   
     arm_joint_5_limit_upper="${1.47}"   
     arm_joint_6_limit_lower="${-2.54}"   
     arm_joint_6_limit_upper="${0.9}"
                           
     j1_offset="${l_arm_j1_offset}"
     j2_offset="${l_arm_j2_offset}"
     j3_offset="${l_arm_j3_offset}"
     j4_offset="${l_arm_j4_offset}"
     j5_offset="${l_arm_j5_offset}"
     j6_offset="${l_arm_j6_offset}">     
    <origin xyz="0.0 0.234 0.165" rpy="0 ${0 + l_arm_j0_offset} 0"/>
  </thor_arm_7dof_simple_with_offsets_macro>  
  
  <!--Variant: utorso is a link without mass with identity transform to first joint-->
  <!--
  <link name="utorso">
  </link>
  
  <thor_arm_7dof_simple_with_offsets_macro parent="utorso" name="l" reflect="1"        
     arm_joint_0_limit_lower="${-M_PI}"
     arm_joint_0_limit_upper="${2.3}"
     arm_joint_1_limit_lower="${-M_PI}"
     arm_joint_1_limit_upper="${0.05}" 
     arm_joint_2_limit_lower="${-M_PI*0.5}"
     arm_joint_2_limit_upper="${M_PI}" 
     arm_joint_3_limit_lower="${-2.9}" 
     arm_joint_3_limit_upper="${0.6}"
     arm_joint_4_limit_lower="${-M_PI}"
     arm_joint_4_limit_upper="${4.71}"  
     arm_joint_5_limit_lower="${-1.47}"   
     arm_joint_5_limit_upper="${1.47}"   
     arm_joint_6_limit_lower="${-2.54}"   
     arm_joint_6_limit_upper="${0.9}"
                           
     j1_offset="${l_arm_j1_offset}"
     j2_offset="${l_arm_j2_offset}"
     j3_offset="${l_arm_j3_offset}"
     j4_offset="${l_arm_j4_offset}"
     j5_offset="${l_arm_j5_offset}"
     j6_offset="${l_arm_j6_offset}">     
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </thor_arm_7dof_simple_with_offsets_macro>
  --> 
      
</robot>
