<?xml version="1.0"?>

<robot  name="thor_arm_7dof" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find thor_mang_description)/urdf/joint_params.xacro" />
  <xacro:include filename="$(find thor_mang_description)/urdf/helper_macros.urdf.xacro.xml" />
  
  <!--Indices starting at 0 from torso-->  
  <property name="arm_joint_0_suffix" value="_shoulder_pitch" />
  <property name="arm_joint_1_suffix" value="_shoulder_roll" />
  <property name="arm_joint_2_suffix" value="_shoulder_yaw" />
  <property name="arm_joint_3_suffix" value="_elbow" />
  <property name="arm_joint_4_suffix" value="_wrist_yaw1" />
  <property name="arm_joint_5_suffix" value="_wrist_roll" />
  <property name="arm_joint_6_suffix" value="_wrist_yaw2" />
  
  
  
  <property name="arm_link_0_y_offset" value="-0.051" />
  <property name="arm_link_2_z_offset" value="-0.027" />    
   
  <macro name="thor_arm_7dof_simple_macro" params="parent name reflect *origin">
    <thor_arm_7dof_simple_with_offsets_macro parent="${parent}" name="${name}" reflect="${reflect}" j1_offset="-1.4" j2_offset="${M_PI*0.5}" j3_offset="-0.6" j4_offset="0.0" j5_offset="0.0">
      <insert_block name="origin"/>
    </thor_arm_7dof_simple_with_offsets_macro>
  </macro>
  
  <macro name="thor_arm_7dof_simple_with_offsets_macro" params="parent name reflect  arm_joint_0_limit_lower arm_joint_0_limit_upper arm_joint_1_limit_lower arm_joint_1_limit_upper arm_joint_2_limit_lower arm_joint_2_limit_upper arm_joint_3_limit_lower arm_joint_3_limit_upper arm_joint_4_limit_lower arm_joint_4_limit_upper arm_joint_5_limit_lower arm_joint_5_limit_upper arm_joint_6_limit_lower arm_joint_6_limit_upper j1_offset j2_offset j3_offset j4_offset j5_offset j6_offset *origin">
  
  <joint name="${name}${arm_joint_0_suffix}" type="revolute">
    <insert_block name="origin"/>
    <parent
      link="${parent}" />
    <child
       link="${name}_arm_shoulder_pitch"/>
    <axis
      xyz="0 ${reflect} 0" />
    <xacro:joint_large_servo_limits_macro lower="${arm_joint_0_limit_lower}" upper="${arm_joint_0_limit_upper}"/>
  </joint>      

  <link name="${name}_arm_shoulder_pitch">
	<inertial>
                <origin xyz="5.65e-03 ${reflect * -39.01e-03} 0" rpy="0 0 0"/>
                <mass value="0.142"/>
                <inertia ixx="83289.816e-09" ixy="${reflect * 13612.340e-09}" ixz="-0.001e-09" iyy="433477.861e-09" iyz="0" izz="422610.245e-09" />
        </inertial>
    
    <xacro:arm_shoulder_pitch_visual_geom_macro reflect="${reflect}" y_offset="${arm_link_0_y_offset]}"/>
    <xacro:arm_shoulder_pitch_collision_geom_macro reflect="${reflect}" y_offset="${arm_link_0_y_offset]}"/>
  </link>
  
  <joint
     name="${name}${arm_joint_1_suffix}"
    type="revolute">
    <origin
      xyz="0.0 0.0 0"
      rpy="${0 + j1_offset} 0 0"
       />
    <parent
      link="${name}_arm_shoulder_pitch" />
    <child
      link="${name}_arm_shoulder_roll" />
    <axis
      xyz="-1 0 0" />
    <xacro:joint_large_servo_limits_macro lower="${arm_joint_1_limit_lower}" upper="${arm_joint_1_limit_upper}"/>
  </joint>
  
    <link name="${name}_arm_shoulder_roll">
    	<inertial>
                <origin xyz="1.3e-03 0 -1.15e-03" rpy="0 0 0"/>
                <mass value="0.937"/>
                <inertia ixx="451426.105e-09" ixy="${reflect * 0.434e-09}" ixz="11412.287e-09" iyy="1483429.746e-09" iyz="${reflect * -0.007e-09}" izz="1474889.397e-09" />
        </inertial>
     
    <xacro:arm_shoulder_roll_visual_geom_macro reflect="${reflect}"/>
    <xacro:arm_shoulder_roll_collision_geom_macro/>
  </link>
  
  <joint name="${name}${arm_joint_2_suffix}" type="revolute">
    <origin
      xyz="0 0 0"
      rpy="0 0 ${0 + j2_offset}"
       />
    <parent
      link="${name}_arm_shoulder_roll" />
    <child
      link="${name}_arm_shoulder_yaw" />
    <axis
      xyz="0 0 -1" />
    <xacro:joint_large_servo_limits_macro lower="${arm_joint_2_limit_lower}" upper="${arm_joint_2_limit_upper}"/>
  </joint>
  
  <link name="${name}_arm_shoulder_yaw">
	<inertial>
                <origin xyz="12.52e-03 ${reflect * -0.07e-03} -165.65e-03" rpy="0 0 0"/>
                <mass value="1.836"/>
                <inertia ixx="12547721.666e-09" ixy="${reflect * -8641.063e-09}" ixz="-1864553.503e-09" iyy="12409562.046e-09" iyz="${reflect * 16900.066e-09}" izz="1956754.834e-09" />
        </inertial>

    <xacro:arm_shoulder_yaw_visual_geom_macro reflect="${reflect}" z_offset="${arm_link_2_z_offset}"/>
    <xacro:arm_shoulder_yaw_collision_geom_macro z_offset="${arm_link_2_z_offset}"/>

  </link>
  
  <joint name="${name}${arm_joint_3_suffix}" type="revolute">
    <origin
      xyz="0.03 0 ${-0.219 + arm_link_2_z_offset}"
      rpy="0 ${0 + j3_offset} 0"
       />
    <parent
      link="${name}_arm_shoulder_yaw" />
    <child
      link="${name}_arm_elbow" />
    <axis
      xyz="0 ${reflect} 0" />
    <xacro:joint_medium_servo_limits_macro lower="${arm_joint_3_limit_lower}" upper="${arm_joint_3_limit_upper}"/>
  </joint>
  
  <link name="${name}_arm_elbow">
	<inertial>
                <origin xyz="-29.58e-03 ${reflect * 2.72e-03} -34.87e-03" rpy="0 0 0"/>
                <mass value="0.132"/>
                <inertia ixx="324345.667e-09" ixy="${reflect * 4992.020e-09}" ixz="17555.129e-09" iyy="100560.943e-09" iyz="${reflect * 7179.039e-09}" izz="338134.190e-09" />
        </inertial>

    <xacro:arm_elbow_visual_geom_macro reflect="${reflect}"/>
    <xacro:arm_elbow_collision_geom_macro />

  </link>
  
  <joint name="${name}${arm_joint_4_suffix}" type="revolute">
    <origin
      xyz="-0.030 0 -0.18600"
      rpy="0 0 ${0 + j4_offset}"
       />
    <parent
      link="${name}_arm_elbow" />
    <child
      link="${name}_arm_wrist_yaw" />
    <axis
      xyz="0 0 -1" />
    <xacro:joint_small_servo_limits_macro lower="${arm_joint_4_limit_lower}" upper="${arm_joint_4_limit_upper}"/>
  </joint>
  
  
  <link name="${name}_arm_wrist_yaw">
    	<inertial>
                <origin xyz="-0.74e-03 0 48.62e-03" rpy="0 0 0"/>
                <mass value="0.838"/>
                <inertia ixx="2137604.574e-09" ixy="${reflect * -0.157e-09}" ixz="28646.979e-09" iyy="2301979.407e-09" iyz="${reflect * -0.259e-09}" izz="434226.705e-09" />
        </inertial>

    <xacro:arm_wrist_yaw_visual_geom_macro reflect="${reflect}"/>
    <xacro:arm_wrist_yaw_collision_geom_macro />

  </link>
  
  <joint name="${name}${arm_joint_5_suffix}" type="revolute">
    <origin
      xyz="0 0 0"
      rpy="${0 + j5_offset} 0 0"
       />
    <parent
      link="${name}_arm_wrist_yaw" />
    <child
      link="${name}_arm_wrist_roll" />
    <axis
      xyz="1 0 0" />
    <xacro:joint_small_servo_limits_macro lower="${arm_joint_5_limit_lower}" upper="${arm_joint_5_limit_upper}"/>
  </joint>
  
  <link name="${name}_arm_wrist_roll">
    	<inertial>
                <origin xyz="0.75e-03 0 -72.98e-03" rpy="0 0 0"/>
                <mass value="0.441"/>
                <inertia ixx="475419.459e-09" ixy="${reflect * 0.001e-09}" ixz="16500.682e-09" iyy="553568.777e-09" iyz="${reflect * 0.001e-09}" izz="213537.589e-09" />
        </inertial>
    
    <xacro:arm_wrist_roll_visual_geom_macro reflect="${reflect}"/>
    <xacro:arm_wrist_roll_collision_geom_macro reflect="${reflect}"/>
    
  </link>
  
  <joint name="${name}${arm_joint_6_suffix}" type="revolute">
    <origin
      xyz="0 0 0"
      rpy="0 0 ${0 + j6_offset}"
       />
    <parent
      link="${name}_arm_wrist_roll" />
    <child
      link="${name}_hand" />
    <axis
      xyz="0 0 -1" />
    <xacro:joint_small_servo_limits_macro lower="${arm_joint_6_limit_lower}" upper="${arm_joint_6_limit_upper}"/>
  </joint>
  
  <link name="${name}_hand">
    <inertial>
                <origin xyz="0 0 -149.34e-03" rpy="0 0 0"/>
                <mass value="0.171"/>
                <inertia ixx="46209.326e-09" ixy="${reflect * -6.454e-09}" ixz="-5.221e-09" iyy="38759.568e-09" iyz="${reflect * 4.139e-09}" izz="55609.8e-09" />
    </inertial>

    <xacro:arm_wrist_yaw2_visual_geom_macro reflect="${reflect}"/>
    <xacro:arm_wrist_yaw2_collision_geom_macro />
    
  </link>
  
<!--    <joint name="${name}_hand_joint" type="fixed">
    <origin
      xyz="0 0 -0.135"
      rpy="0 0 0"/>
    <parent
      link="${name}_arm_wrist_yaw2" />
    <child
      link="${name}_hand" />

  </joint>
  
  <link name="${name}_hand">
  </link>
  -->
  <!--Transmissions for gazebo ros control-->
  <xacro:joint_transmission_macro joint_name="${name}${arm_joint_0_suffix}"/>
  <xacro:joint_transmission_macro joint_name="${name}${arm_joint_1_suffix}"/>
  <xacro:joint_transmission_macro joint_name="${name}${arm_joint_2_suffix}"/>
  <xacro:joint_transmission_macro joint_name="${name}${arm_joint_3_suffix}"/>
  <xacro:joint_transmission_macro joint_name="${name}${arm_joint_4_suffix}"/>
  <xacro:joint_transmission_macro joint_name="${name}${arm_joint_5_suffix}"/>
  <xacro:joint_transmission_macro joint_name="${name}${arm_joint_6_suffix}"/>
  
  <!--Coloring for Gazebo-->
  <xacro:set_gazebo_robot_default_color_macro link_name="${name}_arm_shoulder_pitch" />
  <xacro:set_gazebo_robot_default_color_macro link_name="${name}_arm_shoulder_roll" />
  <xacro:set_gazebo_robot_default_color_macro link_name="${name}_arm_shoulder_yaw" />
  <xacro:set_gazebo_robot_default_color_macro link_name="${name}_arm_elbow" />
  <xacro:set_gazebo_robot_default_color_macro link_name="${name}_arm_wrist_yaw" />
  <xacro:set_gazebo_robot_default_color_macro link_name="${name}_hand" />
  
  </macro>
</robot>

